### ISSUE TITLE
Can this model be commercialized? Why do I see some blogs that say it can be commercialized, but using the space on your huggingface, the display is only for research and experimentation

### ISSUE THREAD

**Issue by libai-lab** [sambanova/bloomchat#3]
Can this model be commercialized? Why do I see some blogs that say it can be commercialized, but using the space on your huggingface, the display is only for research and experimentation

**Comment by phineas-pta** [comment]
you can read the LICENSE

**Comment by libai-lab** [comment]
> you can read the LICENSE

The source code shows that it can be used commercially, but I saw the prompt on huggingface's model that model is available only for research and experimentation.

**Comment by phineas-pta** [comment]
what prompt are you talking about? i don't see it in the LICENSE https://huggingface.co/sambanovasystems/BLOOMChat-176B-v1/tree/main

**Comment by libai-lab** [comment]
> what prompt are you talking about? i don't see it in the LICENSE https://huggingface.co/sambanovasystems/BLOOMChat-176B-v1/tree/main
[](https://huggingface.co/spaces/sambanovasystems/BLOOMChat  )
There will be a prompt when you first enter the page in this space 
![image](https://github.com/sambanova/bloomchat/assets/118711163/6375df01-f1fb-46c3-88a3-de6bbbc2fcdc)

**Comment by phineas-pta** [comment]
i think it applies to the demo only

![image](https://github.com/sambanova/bloomchat/assets/37548991/837d8b81-17e7-4e6f-95fb-c5b35b6b2b5c)

see this

![image](https://github.com/sambanova/bloomchat/assets/37548991/320c49a0-0aa1-48da-9645-822650ed5c2c)

**Comment by libai-lab** [comment]
> i think it applies to the demo only
> 
> ![image](https://user-images.githubusercontent.com/37548991/240956213-837d8b81-17e7-4e6f-95fb-c5b35b6b2b5c.png)
> 
> see this
> 
> ![image](https://user-images.githubusercontent.com/37548991/240956732-320c49a0-0aa1-48da-9645-822650ed5c2c.png)

oh,thank you very much, You helped me so much

**Comment by snova-urmisht** [comment]
Thanks @phineas-pta !
