### ISSUE TITLE
Reasoning ability is not very good

### ISSUE THREAD

**Issue by lucasjinreal** [sambanova/bloomchat#4]
![image](https://github.com/sambanova/bloomchat/assets/21303438/d85d328c-0ae4-4313-9d86-bda00cfc1a67)

A 176B model can not even inference this question, this makes think:

1. Does the data really so matters? since BLOOM already using world languages which should at least have some basic inference sense on different languages, above question if ask in English, it can infer, but Chinese, failed;
2. How many Chinese corpus used in BLOOM training?

BTW, the demo runs very fast.

**Comment by TianY111** [comment]
How many GPUs are needed for inference?
